# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=3, default=0.0, editable=False, max_digits=10)),
            ],
        ),
    ]
