# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=1, default=0.0, editable=False, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=1, default=0.0, editable=False, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
